
const sections=[
['about','التعريف بالمشروع','🌱','الفكرة والأهداف والفوائد والتحديات'],
['outside','تشجير الجانب الخارجي','🌳','متابعة التشجير حول المدرسة'],
['inside','تشجير الجانب الداخلي','🍃','توثيق المساحات الخضراء الداخلية'],
['yard','تشجير ساحة المدرسة','🏫','أنشطة وتشجير ساحة المدرسة'],
['palms','مشروع 200 نخلة','🌴','متابعة مراحل مشروع النخيل'],
['experiments','التجارب الزراعية','🧪','التجارب والنتائج والملاحظات'],
['qitaf','شركة قطاف','🤝','التعاون والأنشطة المشتركة'],
['visits','الزيارات','📍','تسجيل الزيارات والملاحظات'],
['expenses','المصروفات','🧾','إدارة المصروفات بالريال العُماني'],
['supporters','الجهات الداعمة','💚','توثيق الجهات الداعمة للمشروع']
];
const K='ghars-v5-records', A='ghars-v5-admin';
let records=JSON.parse(localStorage.getItem(K)||'[]'), admin=false, current='home';
const $=s=>document.querySelector(s), esc=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(K,JSON.stringify(records))}
function sec(id){return sections.find(x=>x[0]===id)}
function shell(body){return `<header class="top"><div class="logo">🌿</div><div class="brand"><b>غرس وظلال</b><small>مشروع مدرسي للأثر الأخضر</small></div><button class="admin" onclick="adminPanel()">${admin?'لوحة المشرف':'دخول المشرف'}</button></header><main>${body}</main>`}
function home(){current='home';$('#app').innerHTML=shell(`<section class="hero"><small>مشروع غرس وظلال</small><h1>نغرس اليوم.<br><span>ويكبر الظل غداً.</span></h1><p>من غرْسة صغيرة يبدأ الأثر؛ نوثّق مراحل التشجير والأنشطة والتجارب والشراكات في مكان واحد.</p><button onclick="openSec('about')">تعرّف على المشروع ←</button></section><div class="heading"><div><h2>اكتشف أقسام المشروع</h2><small>١٠ مساحات للأثر</small></div></div><section class="grid">${sections.map((s,i)=>`<button class="card" onclick="openSec('${s[0]}')"><div class="ico">${s[2]}</div><h3>${String(i+1).padStart(2,'0')} · ${s[1]}</h3><p>${s[3]}</p><div class="go">السجلات ←</div></button>`).join('')}</section>`)}
function openSec(id){current=id;let s=sec(id), list=records.filter(r=>r.section===id).sort((a,b)=>(b.date||'').localeCompare(a.date||''));$('#app').innerHTML=shell(`<div class="pagehead"><button class="back" onclick="home()">←</button><div><h1>${s[2]} ${s[1]}</h1><small>${s[3]}</small></div></div>${admin?`<div class="toolbar"><button class="primary" onclick="editRecord(null,'${id}')">＋ إضافة سجل</button></div>`:''}<div>${list.length?list.map(r=>recordCard(r)).join(''):`<div class="empty"><div style="font-size:38px">${s[2]}</div><b>لا توجد سجلات بعد</b><span>${admin?'ابدأ بإضافة أول سجل لهذا القسم':'سيظهر محتوى القسم هنا عند إضافته'}</span></div>`}</div>`)}
function recordCard(r){return `<article class="record"><div class="date">${esc(r.date||'')}</div><h3>${esc(r.title)}</h3>${r.body?`<p>${esc(r.body)}</p>`:''}${r.notes?`<div class="notice">ملاحظات: ${esc(r.notes)}</div>`:''}${r.section==='expenses'?`<b>${Number(r.amount||0).toFixed(3)} ر.ع.</b>`:''}${r.section==='palms'&&r.quantity?`<b>عدد النخيل: ${Number(r.quantity)}</b>`:''}${admin?`<div class="actions"><button onclick="editRecord('${r.id}')">تعديل</button><button class="danger" onclick="delRecord('${r.id}')">حذف</button></div>`:''}</article>`}
function adminPanel(){if(!admin){login();return}current='admin';let media=records.reduce((n,r)=>n+(r.mediaCount||0),0), total=records.filter(r=>r.section==='expenses').reduce((n,r)=>n+Number(r.amount||0),0);$('#app').innerHTML=shell(`<div class="pagehead"><button class="back" onclick="home()">←</button><div><h1>⚙️ لوحة المشرف</h1><small>إدارة محتوى غرس وظلال</small></div></div><div class="stats"><div class="stat"><b>${records.length}</b><small>سجل</small></div><div class="stat"><b>${media}</b><small>مرفق</small></div><div class="stat"><b>${total.toFixed(3)}</b><small>ر.ع.</small></div></div><div class="notice">البيانات محفوظة على هذا الجهاز. استخدم النسخة الاحتياطية قبل حذف التطبيق أو بياناته.</div><section class="grid">${sections.map(s=>`<button class="card" onclick="openSec('${s[0]}')"><div class="ico">${s[2]}</div><h3>${s[1]}</h3><p>${records.filter(r=>r.section===s[0]).length} سجل</p><div class="go">إدارة ←</div></button>`).join('')}</section><div class="toolbar"><button class="secondary" onclick="exportData()">تصدير نسخة احتياطية</button><button class="secondary" onclick="importData()">استعادة نسخة</button><button class="secondary danger" onclick="logout()">قفل الإدارة</button></div>`)}
function login(){let exists=localStorage.getItem(A); modal(`<h2>${exists?'دخول المشرف':'إعداد المشرف لأول مرة'}</h2><div class="field"><label>كلمة المرور</label><input id="pw" type="password" minlength="8" placeholder="8 أحرف على الأقل"></div>${exists?'':`<div class="field"><label>تأكيد كلمة المرور</label><input id="pw2" type="password" minlength="8"></div>`}<div id="err" style="color:#a83c32"></div><div class="sheetactions"><button class="primary" onclick="doLogin(${exists?'true':'false'})">${exists?'دخول':'حفظ وفتح الإدارة'}</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>`)}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
function doLogin(exists){let p=$('#pw').value;if(p.length<8){$('#err').textContent='كلمة المرور يجب أن تكون 8 أحرف على الأقل';return}if(!exists){if(p!==$('#pw2').value){$('#err').textContent='كلمتا المرور غير متطابقتين';return}localStorage.setItem(A,hash(p))}else if(localStorage.getItem(A)!==hash(p)){ $('#err').textContent='كلمة المرور غير صحيحة';return}admin=true;closeModal();adminPanel()}
function logout(){admin=false;home()}
function editRecord(id,section){let r=id?records.find(x=>x.id===id):{section,title:'',date:new Date().toISOString().slice(0,10),body:'',notes:'',amount:'',quantity:''};modal(`<h2>${id?'تعديل السجل':'إضافة سجل'}</h2><div class="field"><label>العنوان</label><input id="title" value="${esc(r.title)}"></div><div class="row"><div class="field"><label>التاريخ</label><input id="date" type="date" value="${r.date}"></div><div class="field"><label>الحالة</label><select id="status"><option>نشط</option><option>مكتمل</option><option>مخطط</option></select></div></div><div class="field"><label>الوصف</label><textarea id="body">${esc(r.body)}</textarea></div><div class="field"><label>الملاحظات</label><textarea id="notes">${esc(r.notes)}</textarea></div>${r.section==='expenses'?`<div class="field"><label>المبلغ (ر.ع.)</label><input id="amount" type="number" step=".001" min="0" value="${r.amount||''}"></div>`:''}${r.section==='palms'?`<div class="field"><label>عدد النخيل</label><input id="quantity" type="number" min="0" value="${r.quantity||''}"></div>`:''}<div class="field"><label>الصور والفيديوهات</label><button class="secondary" onclick="pickMedia()">＋ اختيار مرفقات</button><small id="mediaInfo">يمكن اختيار صور أو فيديوهات من الهاتف</small></div><div class="sheetactions"><button class="primary" onclick="storeRecord('${id||''}','${r.section}')">حفظ السجل</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>`); window._mediaCount=r.mediaCount||0}
function pickMedia(){let p=$('#mediaPicker');p.onchange=()=>{window._mediaCount=(window._mediaCount||0)+p.files.length;$('#mediaInfo').textContent=`تم اختيار ${p.files.length} ملف/ملفات (سيُسجل العدد في هذه النسخة المحلية)`};p.click()}
function storeRecord(id,section){let title=$('#title').value.trim();if(!title)return alert('اكتب عنوان السجل');let obj={id:id||crypto.randomUUID(),section,title,date:$('#date').value,body:$('#body').value,notes:$('#notes').value,status:$('#status').value,mediaCount:window._mediaCount||0};if(section==='expenses')obj.amount=Number($('#amount').value||0);if(section==='palms')obj.quantity=Number($('#quantity').value||0);if(id)records=records.map(r=>r.id===id?obj:r);else records.push(obj);save();closeModal();openSec(section)}
function delRecord(id){let r=records.find(x=>x.id===id);if(confirm('حذف هذا السجل؟')){records=records.filter(x=>x.id!==id);save();openSec(r.section)}}
function modal(html){let d=document.createElement('div');d.className='sheet';d.id='modal';d.innerHTML=`<div>${html}</div>`;document.body.appendChild(d)}
function closeModal(){document.querySelector('.sheet')?.remove()}
function exportData(){let b=new Blob([JSON.stringify({version:5,records},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='ghars-wa-zilal-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(){let i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=async()=>{try{let d=JSON.parse(await i.files[0].text());if(!Array.isArray(d.records))throw 0;records=d.records;save();adminPanel();alert('تمت استعادة النسخة الاحتياطية')}catch{alert('ملف النسخة الاحتياطية غير صالح')}};i.click()}
home();
